import Footer from "@/components/shared/footer/footer";
import SupportLayoutHeader from "@/components/shared/supportLayoutHeader/SupportLayoutHeader";

/* 
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */
export default function SupportLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SupportLayoutHeader />
      {children}
      <Footer />
    </>
  );
}
